format = """
[┌───────────────────>](bold green)
[│](bold green)$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$java\
$python\
$aws\
$sudo\
$cmd_duration
[└─>](bold green) """
